name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        working-directory: ./apps/web
        run: npm ci

      # --- DÃ©ploiement via la CLI Vercel ---
      - name: Pull env from Vercel
        working-directory: ./apps/web
        run: npx vercel pull --yes --environment=production --token CvLOdmSg2xAuZft2E4ULUWMQ
        env:
          VERCEL_ORG_ID: team_toms-projects-022d8320
          VERCEL_PROJECT_ID: prj_PyfwcVHTSgaGbqwroS5KB29QgIPr

      - name: Build
        working-directory: ./apps/web
        run: npx vercel build --token CvLOdmSg2xAuZft2E4ULUWMQ
        env:
          VERCEL_ORG_ID: team_toms-projects-022d8320
          VERCEL_PROJECT_ID: prj_PyfwcVHTSgaGbqwroS5KB29QgIPr

      - name: Deploy
        working-directory: ./apps/web
        run: npx vercel deploy --prebuilt --prod --token CvLOdmSg2xAuZft2E4ULUWMQ
        env:
          VERCEL_ORG_ID: team_toms-projects-022d8320
          VERCEL_PROJECT_ID: prj_PyfwcVHTSgaGbqwroS5KB29QgIPr
